<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>
  <body>
    <div class="jumbotron">
      <div class="container">
        <h2 class="display-3">Demo Authentication</h2>
      </div>
    </div>
    <div class="container">
      <div class="row">

        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="card">
            <div class="card-block">
              <h4 class="card-title">Public Area</h4>
              <p class="card-text"><code>{none}</code></p>
              <a href="/public-area" class="btn btn-primary">Go</a>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="card">
            <div class="card-block">
              <h4 class="card-title">Basic Authentication</h4>
              <p class="card-text"><code>basic / pass</code></p>
              <a href="/basic-auth" class="btn btn-primary">Go</a>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="card">
            <div class="card-block">
              <h4 class="card-title">Digest Authentication</h4>
              <p class="card-text"><code>digest / pass</code></p>
              <a href="/digest-auth" class="btn btn-primary">Go</a>
            </div>
          </div>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="card">
            <div class="card-block">
              <h4 class="card-title">Form Authentication</h4>
              <p class="card-text"><code>form / pass</code></p>
              <a href="/dashboard" class="btn btn-primary">Go</a>
            </div>
          </div>
        </div>

      </div>
    </div>

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>